[workspace]
authors = ["Luhan Cheng <0lh.cheng0@gmail.com>"]
channels = ["conda-forge", "anaconda"]
name = "pyalex"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
langchain = "1.0.7.*"
graph-tool = ">=2.98,<3"
langgraph = ">=1.0.3,<2"
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
pydantic = ">=2.12.4,<3"
langchain-openai = ">=1.0.3,<2"
pytest = ">=8,<9"
networkx = ">=3.5,<4"
plotly = ">=6.5.0,<7"
pydot = ">=4.0.1,<5"
graphviz = ">=14.0.4,<15"
treelib = ">=1.7.1,<2"

[pypi-dependencies]
plotly-express = ">=0.4.1, <0.5"
pygraphviz = ">=1.14, <2"
